apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding
  template:
    metadata:
      labels:
        app: onboarding
    spec:
    containers:
      - name: onboarding-container
        image: onboarding-system:latest
        ports:
        - containerPort: 8000
        - containerPort: 8001