apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding
  template:
    metadata:
      labels:
        app: onboarding
    spec:
    containers:
      - name: onboarding-container
        image: ghcr.io/your-username/your-repo/onboarding-system:latest  # Replace with your image
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: PYTHONPATH
          value: "."
---
apiVersion: v1
kind: Service
metadata:
  name: onboarding-service
spec:
  selector:
    app: onboarding
  ports:
  - port: 8000
    targetPort: 8000
    name: fastapi
  - port: 8001
    targetPort: 8001
    name: metrics
  type: LoadBalancer  # Use ClusterIP for internal access