name: CI/CD Pipeline for Onboarding System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        
        python -c "import main; print('App imports successfully')"
        pytest /ests

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/onboarding-system:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/onboarding-system:latest

    # Optional: Deploy to Kubernetes (uncomment and configure for AWS EKS)
    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s-deployment.yaml
    #     kubectl rollout status deployment/onboarding-deployment
    #